// India Gully — Brand Design Tokens & Shared Layout
// Primary Gold: #C5A028  Secondary Dark: #1A1A1A  Accent Light: #F7F3E9

export const BRAND = {
  gold: '#C5A028',
  goldLight: '#D4B445',
  goldDark: '#9E7E1A',
  dark: '#1A1A1A',
  darkMid: '#2D2D2D',
  charcoal: '#3C3C3C',
  warmWhite: '#FAFAF7',
  cream: '#F7F3E9',
  creamDark: '#EDE8D8',
  textPrimary: '#1A1A1A',
  textSecondary: '#5C5C5C',
  textMuted: '#8C8C8C',
  borderLight: '#E8E4D8',
  borderMid: '#D4CEBC',
}

export const META = {
  company: 'India Gully',
  legalName: 'Vivacious Entertainment and Hospitality Pvt. Ltd.',
  tagline: 'Celebrating Desiness',
  taglineFull: 'Celebrating Desiness Across Every Vertical',
  cin: 'U74900DL2017PTC000000',
  gstin: '07XXXXXX000XXX',
  address: 'New Delhi, India',
  email: 'info@indiagully.com',
  phone: '+91 98108 89134',
  website: 'https://indiagully.com',
}

export const TEAM = [
  {
    id: 'arun-manikonda',
    name: 'Arun Manikonda',
    title: 'Managing Director',
    designation: 'Director on Board & KMP',
    phone: '+91 9810889134',
    email: 'akm@indiagully.com',
    initials: 'AM',
  },
  {
    id: 'pavan-manikonda',
    name: 'Pavan Manikonda',
    title: 'Executive Director',
    designation: 'Director on Board & KMP',
    phone: '+91 6282556067',
    email: 'pavan@indiagully.com',
    initials: 'PM',
  },
  {
    id: 'amit-jhingan',
    name: 'Amit Jhingan',
    title: 'President, Real Estate Vertical',
    designation: 'KMP (Not a Director)',
    phone: '+91 9899993543',
    email: 'amit.jhingan@indiagully.com',
    initials: 'AJ',
  },
]

export const VERTICALS = [
  { id: 'real-estate', name: 'Real Estate', icon: '🏛️', desc: 'Transaction advisory, site selection & asset management across commercial and hospitality real estate.' },
  { id: 'retail', name: 'Retail', icon: '🛍️', desc: 'Leasing strategy, brand mix, fit-out coordination and anchor structuring for malls and mixed-use destinations.' },
  { id: 'hospitality', name: 'Hospitality', icon: '🏨', desc: 'Hotel management, brand on-boarding, pre-opening, PMC and feasibility for hotels across India.' },
  { id: 'entertainment', name: 'Entertainment', icon: '🎡', desc: 'Theme parks, FECs, indoor & outdoor entertainment destinations — concept to commissioning.' },
  { id: 'debt-special', name: 'Debt & Special Situations', icon: '⚖️', desc: 'Structured debt advisory, distressed asset resolution and special situation mandates.' },
  { id: 'horeca', name: 'HORECA Solutions', icon: '🍽️', desc: 'End-to-end FF&E, OS&E, kitchen equipment, linen and tableware procurement for hotels and F&B.' },
]

export const STATS = [
  { value: '₹10,000 Cr+', label: 'Advisory Pipeline' },
  { value: '15+', label: 'Hotel Projects' },
  { value: '30+', label: 'Retail Brands' },
  { value: '20+', label: 'Hospitality Brand Partnerships' },
  { value: 'Pan-India', label: 'Presence' },
]

export const LISTINGS = [
  {
    id: 'entertainment-maharashtra',
    title: 'Integrated Entertainment Destination',
    location: 'Maharashtra',
    sector: 'Entertainment',
    value: '₹4,500 Cr',
    status: 'Active Mandate · Exclusive',
    badge: 'Entertainment',
    area: '200+ Acres',
    components: 'Theme Park + Hotel + Retail',
    stage: 'Phase 1 Approved',
    desc: 'Mega integrated entertainment destination combining theme park, luxury hotel tower, F&B street and retail mall across 200+ acres in Maharashtra. First-of-its-kind in India.',
    tags: ['Theme Park', 'Hospitality', 'Entertainment'],
    highlight: true,
  },
  {
    id: 'retail-hub-mumbai',
    title: 'Entertainment & Retail Hub',
    location: 'Mumbai MMR',
    sector: 'Real Estate',
    value: '₹2,100 Cr',
    status: 'Active Mandate · Exclusive',
    badge: 'Real Estate',
    area: '800,000 sq ft',
    preleased: '85%',
    capRate: '8.5%+',
    desc: 'Premium entertainment and retail hub in Mumbai MMR with 85% pre-leased 800,000 sq ft. Strong anchor tenant mix with entertainment and F&B anchors.',
    tags: ['Retail', 'Entertainment', 'Mumbai'],
    highlight: true,
  },
  {
    id: 'heritage-rajasthan',
    title: '6-Property Heritage Hotel Portfolio',
    location: 'Rajasthan',
    sector: 'Heritage',
    value: '₹620 Cr',
    status: 'Under Negotiation',
    badge: 'Heritage',
    properties: '6 Hotels',
    keys: '480 Rooms',
    occupancy: '72% TTM',
    desc: 'Six-property heritage hotel portfolio covering palaces, havelis and colonial estates across Rajasthan. Strong leisure demand and international tourist catchment.',
    tags: ['Heritage', 'Palaces', 'Rajasthan'],
    highlight: false,
  },
  {
    id: 'luxury-resorts-pan-india',
    title: '5-Property Luxury Resort Rollout',
    location: 'Rajasthan · Goa · Kerala',
    sector: 'Hospitality',
    value: '₹350 Cr',
    status: 'Feasibility Stage',
    badge: 'Hospitality',
    properties: '5 Resorts',
    keys: '320 Keys',
    irr: '22–26%',
    desc: 'Five-property luxury resort rollout across top leisure destinations. Projected IRR 22–26% with Marriott flag under negotiation. Shovel-ready at 2 locations.',
    tags: ['Luxury Resort', 'Marriott', 'Pan-India'],
    highlight: false,
  },
  {
    id: 'entertainment-ncr-bhutani',
    title: 'Entertainment City — Delhi NCR (Bhutani)',
    location: 'Noida, Delhi NCR',
    sector: 'Entertainment',
    value: '₹1,200 Cr+',
    status: 'Co-Advisory · Exclusive',
    badge: 'Entertainment',
    gla: '1.5 Mn sq ft',
    partner: 'Bhutani Group',
    desc: '1.5 Mn sq ft entertainment city in Noida NCR co-advised with Bhutani Group. High footfall location adjacent to upcoming metro corridor.',
    tags: ['Entertainment City', 'NCR', 'Bhutani'],
    highlight: true,
  },
  {
    id: 'desi-brand-retail',
    title: 'Desi Brand — 15-City Retail Expansion',
    location: 'Tier 1 & 2 Cities',
    sector: 'Retail',
    value: '₹45 Cr',
    status: 'Active Mandate',
    badge: 'Retail',
    locations: '15 Cities',
    storeSize: '1,200–2,500 sq ft',
    payback: '36 Months',
    desc: 'Pan-India retail franchise expansion for Desi Brand across 15 Tier-1 and Tier-2 cities. Strong unit economics with proven 36-month payback period.',
    tags: ['Retail Franchise', 'Pan-India'],
    highlight: false,
  },
]
